// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'button': string;
  'groups': string;
  'spinner': string;
}
export const cssExports: CssExports;
export default cssExports;
